### ISSUE TITLE
help with being able to use the application

### ISSUE THREAD

**Issue by xoceunder** [zGrav/xtream-iptv-player-v3#1]
help with being able to use the application I'm trying to be able to see where to put the data of the server and if there is something else to do to the xtream coder panel

**Comment by zGrav** [comment]
You just put in a username, password and a host. Thats it mate

**Comment by xoceunder** [comment]
that's right but he did not give access

**Comment by xoceunder** [comment]
how can I remove the host field from the login and place the host in the code so that users do not have to add them themselves just add the user and pass

**Comment by zGrav** [comment]
Again, you edit Login.

**Comment by xoceunder** [comment]
and in what line I have to edit I do not know much about this android could you help me please and thank you
