### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by BlackGlassSkin** [zGrav/xtream-iptv-player-v3#11]
Thanks fo your work!!!

Does not start ,after installing the application show
pop up info application error
Compiled with android-studio-ide

What else can I do

**Comment by FelipeTartarotti** [comment]
What error are u getting?

**Comment by BlackGlassSkin** [comment]
the application has stopped working

**### x**   close the application

**Comment by zGrav** [comment]
Check logcat, you should get an error and a stack trace as to why.
