### ISSUE TITLE
Duplicate Channels Not Showing in Guide/EPG

### ISSUE THREAD

**Issue by IPLIVECO** [zGrav/xtream-iptv-player-v3#2]
Hi, I two types of channels in my panel formatted as such:

News Channel (HD)
News Channel (SD)

All of the streams from my IPTV panel show in the Streams list but in the Guide/EPG, it only shows one of the two choices (usually SD). Any idea as to why this is and/or how to fix it? P.S. I have already tried the show all channels settings option
Thank you!!

**Comment by zGrav** [comment]
Hey,

Please send me via email a test account + server info so I can test it.

Thanks.
