### ISSUE TITLE
EPG support on channel MENU bar from default player

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [zGrav/xtream-iptv-player-v3#6]
Hiya

First of all let me say what a nice piece of app you have written

i have managed to compile it and gave it a tryout on a android mobile phone, and also on a Mxq Pro STB i have..

the only thing i have missed to make this a 101% perfect application was to add EPG on the main player menu bar, near the right menu side bar with the channel name and icons..

is this hard to add the controllers to fetch the EPG and display it below?

something like on this picture from the link below

could you give me some guidance on which player controllers i could try to play with to add the epg code on to it?

https://lh3.googleusercontent.com/CRk1y-VfM-D-K-R6Lny1synazoeI_hSyWLsZ1MU35qN3HrTXSje3W6OpOuBbvhjOEDY=w1600-h754-rw

https://www.infinityiptv.com.br/assets/images/perfect-player-1024x532.jpg

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hiya 

its working, further testing managed to get it working on ijk media player



but now i have another weird issue

i tested the app on my Asus zenfone and it works great , EPG working, all functions work great using mpegts stream ..


so i installed same version compiled apk on my STB mxq pro Amlogic S905 , and tv channels dont work on default player1 ijk..
i can only get it working with mx player and vlc player

android version 5.1.1 on the AMLOGIC STB

when i enter the live channel it simply returns to the main menu of the channels.. it does not play

do i need to install any library or codec on the AMLOGIC STB?

**Comment by xoceunder** [comment]
you should share the code

**Comment by AlbertEinsteinGlitchPoint** [comment]
I am confused, what code? I am using 
The public cose from this github, did

**Comment by xoceunder** [comment]
you have the apk already working to see how was the improvement that you are doing

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hiya

i have not made any changes on the code yet, i simply just cloned github and compiled your application, after i tested install apk on STB and Phone..

Player1 default and Player2 dont play mpegts streams h264 direct.. can only play mpeg2 sd channels..

only VLC player can play mpeg4 streams hd channels.

this is the only test i make, not changed any code yet..
